// Nexhr_v2_frontend/src/components/PasswordStrength.tsx
import { evaluatePasswordStrength } from '../utils/passwordStrength';
import './PasswordStrength.css';

export function PasswordStrength({ password }: { password: string }) {
  if (!password) {
    return null;
  }

  const strength = evaluatePasswordStrength(password);
  const labelClass = strength.label.toLowerCase();
  const barWidth = `${(strength.score / 5) * 100}%`;

  return (
    <div className="strength" aria-live="polite">
      <div className="strength__header">
        <span>Password strength</span>
        <span className={`strength__label strength__label--${labelClass}`}>
          {strength.label}
        </span>
      </div>
      <div
        className="strength__bar"
        role="progressbar"
        aria-valuenow={strength.score}
        aria-valuemin={0}
        aria-valuemax={5}
      >
        <span
          className={`strength__fill strength__fill--${labelClass}`}
          style={{ width: barWidth }}
        />
      </div>
      <ul className="strength__checks">
        <li className={strength.checks.length ? 'is-met' : undefined}>More than 8 characters</li>
        <li className={strength.checks.uppercase ? 'is-met' : undefined}>Uppercase letter</li>
        <li className={strength.checks.lowercase ? 'is-met' : undefined}>Lowercase letter</li>
        <li className={strength.checks.number ? 'is-met' : undefined}>Number</li>
        <li className={strength.checks.special ? 'is-met' : undefined}>Special character</li>
      </ul>
    </div>
  );
}

// Frontend/src/app/shared/components/password-strength/password-strength.component.ts
import { Component, computed, input } from '@angular/core';

import { evaluatePasswordStrength } from '../../utils/form.utils';

@Component({
  selector: 'app-password-strength',
  standalone: true,
  templateUrl: './password-strength.component.html',
  styleUrl: './password-strength.component.scss',
})
export class PasswordStrengthComponent {
  readonly password = input('');

  readonly strength = computed(() => evaluatePasswordStrength(this.password()));

  readonly barWidth = computed(() => `${(this.strength().score / 5) * 100}%`);
}

@if (password()) {
  <div class="strength" aria-live="polite">
    <div class="strength__header">
      <span>Password strength</span>
      <span class="strength__label strength__label--{{ strength().label.toLowerCase() }}">
        {{ strength().label }}
      </span>
    </div>
    <div class="strength__bar" role="progressbar" [attr.aria-valuenow]="strength().score" aria-valuemin="0" aria-valuemax="5">
      <span class="strength__fill strength__fill--{{ strength().label.toLowerCase() }}" [style.width]="barWidth()"></span>
    </div>
    <ul class="strength__checks">
      <li [class.is-met]="strength().checks.length">More than 8 characters</li>
      <li [class.is-met]="strength().checks.uppercase">Uppercase letter</li>
      <li [class.is-met]="strength().checks.lowercase">Lowercase letter</li>
      <li [class.is-met]="strength().checks.number">Number</li>
      <li [class.is-met]="strength().checks.special">Special character</li>
    </ul>
  </div>
}
