// Nexhr_v2_frontend/src/components/AuthLayout.tsx
import { Outlet, useLocation } from 'react-router-dom';
import { BrandMark } from './BrandMark';
import './AuthLayout.css';

export function AuthLayout() {
  const location = useLocation();
  const isLoginLike =
    location.pathname.startsWith('/auth/login') ||
    location.pathname.startsWith('/auth/forgot-password') ||
    location.pathname.startsWith('/auth/reset-password');
  const isWide = location.pathname.startsWith('/organizations');

  return (
    <div
      className={[
        'auth-layout',
        isLoginLike ? 'auth-layout--login' : '',
        isWide ? 'auth-layout--wide' : '',
      ]
        .filter(Boolean)
        .join(' ')}
    >
      {!isWide ? (
        <div className="auth-layout__panel auth-layout__panel--brand">
          {isLoginLike ? (
            <div className="auth-layout__ambiance" aria-hidden="true">
              <span className="auth-layout__orb auth-layout__orb--a" />
              <span className="auth-layout__orb auth-layout__orb--b" />
              <span className="auth-layout__orb auth-layout__orb--c" />
              <span className="auth-layout__sheen" />
            </div>
          ) : null}

          <div className="auth-layout__brand">
            <BrandMark size="lg" tone={isLoginLike ? 'inverse' : 'default'} />
            <h1 className="auth-layout__headline">Modern HR operations for every industry.</h1>
            <p className="auth-layout__copy">
              Secure access to your NexHr workspace with enterprise-grade authentication and a
              polished experience built for teams that scale.
            </p>

            {isLoginLike ? (
              <>
                <ul className="auth-layout__perks" aria-label="Why NexHr">
                  <li>
                    <span className="auth-layout__perk-icon" aria-hidden="true">
                      ✓
                    </span>
                    <div>
                      <strong>One workspace</strong>
                      <span>People, identity, and org access in one place</span>
                    </div>
                  </li>
                  <li>
                    <span className="auth-layout__perk-icon" aria-hidden="true">
                      ✓
                    </span>
                    <div>
                      <strong>Secure sign-in</strong>
                      <span>Protected sessions with organization context</span>
                    </div>
                  </li>
                  <li>
                    <span className="auth-layout__perk-icon" aria-hidden="true">
                      ✓
                    </span>
                    <div>
                      <strong>Built to scale</strong>
                      <span>From first hire through full lifecycle management</span>
                    </div>
                  </li>
                </ul>
                <p className="auth-layout__org-note">
                  Sign in with the email you used when your organization was set up.
                </p>
              </>
            ) : (
              <p className="auth-layout__org-note">Create your account to get started with NexHr.</p>
            )}
          </div>
        </div>
      ) : null}

      <div className="auth-layout__panel auth-layout__panel--form">
        <div className="auth-layout__form-shell">
          <div className="auth-layout__mobile-brand">
            <BrandMark size="sm" showWordmark />
          </div>
          <div className="auth-layout__outlet">
            <Outlet />
          </div>
        </div>
      </div>
    </div>
  );
}

// Frontend/src/app/layouts/auth-layout/auth-layout.component.ts
import { Component, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterOutlet } from '@angular/router';
import { filter } from 'rxjs';

import { routeAnimations } from '../../core/animations/route.animations';
import { BrandMarkComponent } from '../../shared/components/brand-mark/brand-mark.component';

@Component({
  selector: 'app-auth-layout',
  standalone: true,
  imports: [RouterOutlet, BrandMarkComponent],
  templateUrl: './auth-layout.component.html',
  styleUrl: './auth-layout.component.scss',
  animations: [routeAnimations],
})
export class AuthLayoutComponent {
  private readonly router = inject(Router);

  readonly loginLayout = signal(this.isLoginRoute(this.router.url));

  constructor() {
    this.router.events
      .pipe(
        filter((event): event is NavigationEnd => event instanceof NavigationEnd),
        takeUntilDestroyed(),
      )
      .subscribe((event) => {
        this.loginLayout.set(this.isLoginRoute(event.urlAfterRedirects));
      });
  }

  getRouteAnimation(outlet: RouterOutlet | null | undefined): string {
    if (!outlet?.isActivated) {
      return 'idle';
    }

    const animation = outlet.activatedRouteData?.['animation'];
    if (typeof animation === 'string' && animation.length > 0) {
      return animation;
    }

    return outlet.activatedRoute.snapshot.url.map((segment) => segment.path).join('/') || 'route';
  }

  private isLoginRoute(url: string): boolean {
    return (
      url.startsWith('/auth/login') ||
      url.startsWith('/auth/forgot-password') ||
      url.startsWith('/auth/reset-password')
    );
  }
}

<div class="auth-layout" [class.auth-layout--login]="loginLayout()">
  <div class="auth-layout__panel auth-layout__panel--brand">
    <div class="auth-layout__ambiance" aria-hidden="true">
      <span class="auth-layout__orb auth-layout__orb--a"></span>
      <span class="auth-layout__orb auth-layout__orb--b"></span>
      <span class="auth-layout__orb auth-layout__orb--c"></span>
      <span class="auth-layout__sheen"></span>
    </div>

    <div class="auth-layout__brand">
      <app-brand-mark size="lg" tone="inverse" />
      <h1 class="auth-layout__headline">Modern HR operations for every industry.</h1>
      <p class="auth-layout__copy">
        Secure access to NexHr with enterprise-grade authentication and a polished experience built
        for teams that scale.
      </p>

      @if (loginLayout()) {
        <ul class="auth-layout__perks" aria-label="Why NexHr">
          <li>
            <span class="auth-layout__perk-icon" aria-hidden="true">✓</span>
            <div>
              <strong>One platform</strong>
              <span>Enterprise HR workflows in one secure workspace</span>
            </div>
          </li>
          <li>
            <span class="auth-layout__perk-icon" aria-hidden="true">✓</span>
            <div>
              <strong>Secure sign-in</strong>
              <span>Protected sessions with token refresh and remember me</span>
            </div>
          </li>
          <li>
            <span class="auth-layout__perk-icon" aria-hidden="true">✓</span>
            <div>
              <strong>Built to scale</strong>
              <span>From first hire through full lifecycle management</span>
            </div>
          </li>
        </ul>
        <p class="auth-layout__org-note">Sign in with the email associated with your account.</p>
      } @else {
        <p class="auth-layout__org-note">Create your account to get started with NexHr.</p>
      }
    </div>
  </div>

  <div class="auth-layout__panel auth-layout__panel--form">
    <div class="auth-layout__form-shell">
      <div class="auth-layout__mobile-brand">
        <app-brand-mark size="sm" [showWordmark]="true" />
      </div>
      <div class="auth-layout__outlet" [@routeAnimations]="getRouteAnimation(outlet)">
        <router-outlet #outlet="outlet" />
      </div>
    </div>
  </div>
</div>
