// Nexhr_v2_frontend/src/components/BrandMark.tsx
import './BrandMark.css';

type BrandMarkProps = {
  size?: 'sm' | 'lg';
  tone?: 'default' | 'inverse';
  showWordmark?: boolean;
};

export function BrandMark({
  size = 'sm',
  tone = 'default',
  showWordmark = true,
}: BrandMarkProps) {
  return (
    <div className={`brand-mark brand-mark--${size} brand-mark--${tone}`}>
      <span className="brand-mark__badge" aria-hidden="true">
        N
      </span>
      {showWordmark ? (
        <div className="brand-mark__text">
          <strong>NexHr</strong>
          <span>Enterprise HR Platform</span>
        </div>
      ) : null}
    </div>
  );
}

// Frontend/src/app/shared/components/brand-mark/brand-mark.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-brand-mark',
  standalone: true,
  templateUrl: './brand-mark.component.html',
  styleUrl: './brand-mark.component.scss',
})
export class BrandMarkComponent {
  readonly size = input<'sm' | 'md' | 'lg'>('md');
  readonly showWordmark = input(true);
  readonly tone = input<'default' | 'inverse'>('default');
}

<div class="brand" [class]="'brand--' + size()" [class.brand--inverse]="tone() === 'inverse'">
  <div class="brand__mark" aria-hidden="true">
    <span class="brand__glyph">N</span>
  </div>
  @if (showWordmark()) {
    <div class="brand__text">
      <span class="brand__name">NexHr</span>
      <span class="brand__tagline">Enterprise HR Platform</span>
    </div>
  }
</div>
